name: Iglunix Bootstrap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [ x86_64, aarch64, riscv64 ]
      fail-fast: false

    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            bmake \
            wget \
            curl \
            unzip \
            patch \
            perl \
            python3 \
            pkg-config \
            qemu-user-static \
            qemu-user \
            binfmt-support

      - name: Remove conflicting LLVM packages
        run: |
          # Remove existing LLVM packages to avoid conflicts
          sudo apt-get remove -y \
            clang* \
            llvm* \
            libc++* \
            libc++abi* \
            libclang* \
            lld* || true
          sudo apt-get autoremove -y
          sudo rm -rf /usr/lib/llvm-* /usr/lib/cmake/clang* /usr/lib/cmake/llvm*

      - name: Install LLVM/Clang toolchain
        run: |
          # Use the official LLVM installation script
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21 all
          
          # Set up alternatives for LLVM 21
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-21 100
          sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-21 100
          sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-21 100
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-21 100

      - name: Verify toolchain
        run: |
          clang --version
          clang++ --version
          ld.lld --version
          llvm-ar --version

      - name: Set up build environment
        run: |
          # Replace samu with ninja in scripts
          find . -name "*.sh" -exec sed -i 's/samu/ninja/g' {} \;
          
          # Make scripts executable
          chmod +x *.sh
          
          # Create necessary directories
          mkdir -p src build sysroot
          
          # Set up QEMU binfmt for cross-architecture execution
          sudo systemctl restart systemd-binfmt
          
          # Verify QEMU emulators are available
          which qemu-aarch64-static || echo "qemu-aarch64-static not found"
          which qemu-riscv64-static || echo "qemu-riscv64-static not found"
          
          # Create symlinks for QEMU emulators without -static suffix
          sudo ln -sf /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64 || true
          sudo ln -sf /usr/bin/qemu-riscv64-static /usr/bin/qemu-riscv64 || true

      - name: Run bootstrap for ${{ matrix.arch }}
        run: |
          export CC=clang
          export CXX=clang++
          export AR=llvm-ar
          export RANLIB=llvm-ranlib
          export STRIP=llvm-strip
          export CMAKE_PREFIX_PATH=/usr/lib/llvm-21
          export LLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm
          export Clang_DIR=/usr/lib/llvm-21/lib/cmake/clang
          ./boot.sh ${{ matrix.arch }}

      - name: Verify build outputs
        run: |
          ls -la sysroot/
          ls -la sysroot/usr/
          find sysroot/usr/bin -type f | head -10 || true
          find sysroot/usr/lib -name "*.so*" | head -10 || true

      - name: Upload sysroot artifact
        uses: actions/upload-artifact@v4
        with:
          name: iglunix-sysroot-${{ matrix.arch }}
          path: sysroot/
          retention-days: 7

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.arch }}
          path: |
            *.log
            build/
          retention-days: 3
